INSERT INTO `Architecture` VALUES (1,'All','','defined __i386__');
INSERT INTO `Architecture` VALUES (2,'IA32','http://www.intel.com/','defined __i386__');
INSERT INTO `Architecture` VALUES (3,'IA64','http://www.intel.com/','defined __i386__');
INSERT INTO `Architecture` VALUES (6,'PPC32','','defined __i386__');
INSERT INTO `Architecture` VALUES (9,'PPC64','','defined __i386__');
INSERT INTO `Architecture` VALUES (10,'S390','','defined __i386__');
INSERT INTO `Architecture` VALUES (11,'x86-64','','defined __i386__');
INSERT INTO `Architecture` VALUES (12,'S390X','','defined __i386__');
