INSERT INTO `Architecture` VALUES (1,'All','','1','1.0',NULL,NULL);
INSERT INTO `Architecture` VALUES (2,'IA32','http://www.intel.com/','defined __i386__','1.0',NULL,NULL);
INSERT INTO `Architecture` VALUES (3,'IA64','http://www.intel.com/','defined __ia64__','1.3',NULL,NULL);
INSERT INTO `Architecture` VALUES (6,'PPC32','','defined __powerpc__ && !defined __powerpc64__','1.2',NULL,NULL);
INSERT INTO `Architecture` VALUES (9,'PPC64','','defined __powerpc64__','2.0',NULL,NULL);
INSERT INTO `Architecture` VALUES (10,'S390','','defined __s390__ && !defined __s390x__','1.3',NULL,NULL);
INSERT INTO `Architecture` VALUES (11,'x86-64','','defined __x86_64__','2.0',NULL,NULL);
INSERT INTO `Architecture` VALUES (12,'S390X','','defined __s390x__','1.3',NULL,NULL);
