
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `Command`;
CREATE TABLE `Command` (
  `Cid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Cname` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `Cpath` varchar(255) DEFAULT NULL,
  `Cdocumented` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ctested` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ccandidatefor` varchar(255) DEFAULT NULL,
  `Cbuiltin` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Cdeprecatedsince` varchar(5) DEFAULT NULL,
  `Cappearedin` varchar(5) NOT NULL DEFAULT '',
  `Cwithdrawnin` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`Cid`),
  UNIQUE KEY `Cname` (`Cname`,`Cpath`),
  KEY `Cdeprecatedsince` (`Cdeprecatedsince`),
  KEY `k_appearedin` (`Cappearedin`,`Cwithdrawnin`),
  KEY `k_withdrawnin` (`Cwithdrawnin`)
) ENGINE=MyISAM AUTO_INCREMENT=1080 DEFAULT CHARSET=latin1;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

