INSERT INTO `Module` VALUES (1,'LSB-Core','Core LSB Specification');
INSERT INTO `Module` VALUES (2,'LSB-CXX','LSB C++ Specification');
INSERT INTO `Module` VALUES (3,'LSB-Desktop','LSB Desktop Specification');
INSERT INTO `Module` VALUES (4,'LSB-Languages','LSB Languages Specification');
INSERT INTO `Module` VALUES (5,'LSB-Printing','LSB Printing Specification');
INSERT INTO `Module` VALUES (6,'LSB-TrialUse','LSB Trial Use Modules');
