INSERT INTO `TestSuite` VALUES (7,'LSB-VSW4','X VSW4 Tests','FSG-LSB','Yes','X11 Test (Vsw4)','','3.1','3.2');
INSERT INTO `TestSuite` VALUES (18,'Desktop_XML2','Desktop XML2','Linux Foundation','Yes','Desktop Tests','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (19,'Desktop_libpng','Desktop libpng','Linux Foundation','Yes','Desktop Tests','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (20,'Libstdcpp','libstdcpp','Linux Foundation','Yes','LibStdC++ Test','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (21,'Desktop_GtkVts','Desktop Gtk','Linux Foundation','Yes','Desktop Tests','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (22,'RuntimeTests','Runtime Tests','Linux Foundation','Yes','Core Test','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (23,'Desktop_Qt','Desktop_Qt','Linux Foundation','Yes','Desktop Tests','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (24,'Desktop_Qt3','Desktop_Qt3','Linux Foundation','Yes','Desktop Tests','','3.1',NULL);
INSERT INTO `TestSuite` VALUES (25,'Xts5','Xts5','Linux Foundation','Yes','X11 Test (Xts5)','','3.2',NULL);
