
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `TypeMember`;
CREATE TABLE `TypeMember` (
  `TMid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TMname` varchar(255) NOT NULL DEFAULT '',
  `TMtypeid` int(10) unsigned NOT NULL DEFAULT '0',
  `TMposition` int(11) NOT NULL DEFAULT '0',
  `TMdescription` varchar(255) NOT NULL DEFAULT '',
  `TMmemberof` int(10) unsigned NOT NULL DEFAULT '0',
  `TMarray` varchar(128) DEFAULT NULL,
  `TMbitfield` tinyint(4) NOT NULL DEFAULT '0',
  `TMtypetype` int(10) unsigned NOT NULL DEFAULT '0',
  `TMwithdrawnin` varchar(5) DEFAULT NULL,
  `TMappearedin` varchar(5) NOT NULL,
  `TMaid` int(10) unsigned NOT NULL DEFAULT '1',
  `TMaccess` enum('public','private','protected') DEFAULT NULL,
  `TMvalue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TMid`),
  KEY `k_TMposmem` (`TMposition`,`TMmemberof`),
  KEY `k_TMtypeid` (`TMtypeid`),
  KEY `k_TMaid` (`TMaid`),
  KEY `k_TMappearedin` (`TMappearedin`,`TMwithdrawnin`),
  KEY `k_TMmemberof` (`TMmemberof`,`TMaid`,`TMappearedin`)
) ENGINE=MyISAM AUTO_INCREMENT=232945 DEFAULT CHARSET=latin1;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

